apiVersion: apps/v1
kind: Deployment
metadata:
  name: starship-web
  namespace: starship-pub
  labels:
    app: starship-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starship-web
  template:
    metadata:
      labels:
        app: starship-web
    spec:
      containers:
      - name: starship-web
        image: docker.io/clfray/starship-web-pub:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
