apiVersion: v1
kind: Service
metadata:
  name: starship-web-service
  namespace: starship-pub
spec:
  selector:
    app: starship-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
